### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by Pschittt** [fabtesta/synology-surveillance-api-motion-telegram-gifs#1]
Hello,

I’d like to test your script.
Could you provide the config file format and data expected ?

If you have a dockerfile, it could be helpful too.

**Comment by fabtesta** [comment]
Hi and sorry for the super late response.

{
  "data_folder": "data",
  "synology_base_api_url": "your syno base url",
  "synology_user": "your syno user with access to surveillance",
  "synology_password": "your syno user's pwd with access to surveillance",
  "synology_cameras": [{
    "id": your camera id,
    "name": "description"
  }],
  "telegram_bot_token": "your telegrambot token",
  "chat_id": "send a message to your bot and get the chat id from bot api url"
}
